Task to import container images to nodes
ppc64le-cloud/k8s-ansible pull request #75
Opened 2024-10-25 12:24 UTC by Rajalakshmi-Girish

This task added would import the ctr images from .tar files in /usr/local/bin.

In the below test run, have displayed the verbose of `kubeadm init` and made sure images are not pulled and used from existing ones in runtime.
Test Run: https://storage.googleapis.com/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1849756631768764416/build-log.txt

2024-10-25 12:34 UTC, mkumatag requested changes

2024-10-25 12:34 UTC, mkumatag commented on roles/download-k8s/tasks/main.yml
> +    find /usr/local/bin -name "*.tar" -print | xargs -L 1 ctr -n k8s.io images import
this logic goes for a toss if we have some other tars in that directory, lets list iterate over only the images required to stand up the cluster

2024-10-25 12:34 UTC, mkumatag commented on roles/download-k8s/tasks/main.yml
> +    export ARCH=ppc64le
can this be generic and populated runtime based on the uname?

2024-10-25 14:33 UTC, mkumatag approved these changes
/lgtm

2024-10-25 14:33 UTC, merged

2024-10-25 14:34 UTC, mkumatag commented
lets update the kubetest2-plugins repo as well

2024-10-26 05:09 UTC, Rajalakshmi-Girish commented
> lets update the kubetest2-plugins repo as well

@mkumatag PTAL https://github.com/ppc64le-cloud/kubetest2-plugins/pull/170